== Сравнение результатов работы группы №1 с результатами работы группы № 4

=== Сходства:

- обе команды начали с проверки работы предполагаемой основной функциональности;
- записывали выполненные действия, фиксировали шаги и реакцию программы.

Почему важно: фиксировали поведение программы при различных условиях, т.е. проводили её исследование. В случае предоставления требований можно будет сличить ожидаемое и фактическое поведение программы, сократить набор тестовых сценариев исходя из требований уже покрытых проверками при проведении исследовательского тестирования.

=== Различия:

- Группа №4 выделила одного человека ответственного за заполнение таблицы.

Почему важно: документ имеет одинаковую структуру, как по форме оформления, так и по применяемым конструкциям языка, что делает его удобнее для чтения, дальнейшей фильтрации/ группировки и т.д.

- Группа № 4 изначально определила стратегию тестирования и следовала ей.

Почему **особенно важно**: Наличие и следование стратегии позволило более быстро и структурировано изучить возможности системы на уровне сценариев использования и перейти к изучению более детальному: поиску ограничений полей и проверки конкретных сценариев.


== *Стратегия тестирования*


=== **Что тестируем**
Web-приложение http://qa-games.ru/

Бизнес-цель данного приложения - создать альтернативу платформе Tumblr, на некоммерческой основе, и вернуть фанатам их 2013-2017.

=== Цель проведения тестирования

* Провести исследовательское тестирование для изучения системы.
* Зафиксировать полученные ответы и состояние системы с целью возможности дальнейшего сличения её фактического и ожидаемого поведения после получения требований.

=== Имеющаяся информация о системе

Приложение представляет из себя ленту с постами различных пользователей.
Предполагается, что пользователь приложения может:

* создать свою учетную запись
* в рамках своей учетной записи:
- создавать посты
- редактировать свои посты
- удалять свои посты
- просматривать добавленные другими пользователями посты
- осуществлять поиск по постам


=== Подход к тестированию

Предполагается, что приложение имеет трехуровневую систему состоящую из Frontend с GUI, API и базы данных.
Frontend в свою очередь имеет следующие основные компоненты:

- Форма регистрации;
- Форма авторизации;
- Область опубликованных постов;
- Кнопка удаления поста;
- Форма создания поста;
- Форма редактирования поста;
- Форма поиска по постам.


Тестирование будет проводиться путем взаимодействия с GUI, что при выполнении потенциальных сценариев использования позволит оценить корректность работы и взаимодействия всех уровней системы. При этом в процессе тестирования и изучения приложения также будет произведено условное разделение GUI на компоненты для тестирования каждого компонента. (Например: Страница – Форма - поля и кнопки).

В процессе работы будут применены следующие типы тестирования:

- Функциональное тестирование применительно к системе и компонентам GUI с целью изучения их поведения.

- Нефункциональное тестирование GUI с целью оценки удобства пользования в части субъективной оценки понятности назначения графических элементов системы (Оценка очевидности, зачем нужно конкретное поле/кнопка/иконка и прочее.

При проведении функционального тестирования планируется применение следующих  техник тест-дизайна:

- Cause-effect – для определения факторов приводящих к определенному результату;
- Эквивалентное разбиение – для оптимизации количества проверок, в случае когда можно выделить эквивалентные наборы входных данных;
- Анализ граничных значений – для оптимизации количества проверок, в случае, когда эквивалентные наборы входных данных являются интервалами;
- Попарное тестирование (Pairwise) - для оптимизации количества проверок,  в случае, когда на результат проверки влияет значение сразу нескольких параметров.

После выполнений предыдущих пунктов будут выделены тестовые сценарии системного интеграционного тестирования для проверки корректной работы и взаимодействия всех уровней приложения (Frontend -API-база данных).

=== Окружение
В связи с отсутствием требований к окружению было принято решение о проведении тестирования  на двух самых популярных в 2022 России десктопных браузерах Google Chrome,  Яндекс.Браузер (источник - https://radar.yandex.ru/browsers?device-category=1&selected_rows=Ct58LP%252CRysHuf%252C%252BjXhkh).

Тестирование на мобильных платформах и других браузерах на данном этапе проводится не будет, в связи ограниченностью временных ресурсов.

=== Ресурсы:

* Технические: Портативный компьютер ОС Windows 10 - 1 шт.;
* Человеческие: Тестировщик – 1 человек;
* Временные: срок до 29.11.2022 10:00.


=== Зависимости:
Данные для авторизации:
log: user1@example.com,
pass: Wan-Rockslide.

Описание API: https://www.notion.so/API-f5d28fa5d73647a18801e1ca69be5170

=== Риски
* 1. Документация:
- в связи с отсутствием развернутого описания приложения, его архитектуры, данных о стабильности версии осложнен анализ необходимых временных ресурсов для  проведения тестирования, а также предварительный дизайн тестовых случаев;
- отсутствие данных о требуемом окружении;
- в связи с отсутствием развернутого описания требований к приложению имеется повышенный риск выявления несоответствий потребностям пользователей;
* 2. Ресурсы:
- крайний срок сдачи проекта - 29.11.2022 до 10:00. В связи с отсутствием понимания масштабов приложения, а также загрузкой тестировщика вне данного проекта необходимо обратить внимание на возможную недостаточность временного ресурса и рассмотреть сверхурочную работу над проектом.



=== Отчетность
По результатам выполнения работы будет предоставлен отчет содержащий список выполненных проверок, ответов системы, а также информация о потенциальных дефектах.