= [middle] Ошибка "500 Internal Server Error" при изменении заголовка поста на  значение совпадающее с заголовком уже имеющегося поста
** ID: QAG-5
** Критичность дефекта: Значительный

** Шаги воспроизведения:
* 1. Авторизоваться на http://qa-games.ru/;
* 2. Добавить новый пост;
* 3. В окне редактирования изменить заголовок поста из шага 2, заменив значение заголовка на значение совпадающее с
заголовком другого уже опубликованного поста;
* 4. Кликнуть кнопку "Сохранить".

** ОР:
1. Всплывает сообщение о том, что заголовок поста должен быть уникальным;
2. Код и статус ответа "400 Bad Request"
3. Пост не отредактирован.

** ФР:
1. Всплывает  сообщение об ошибке "Ошибка сервера, Пожалуйста, попробуйте ещё раз."
2. Код и статус ответа "500 Internal Server Error"
3. Тело ответа содержит:

 {"timestamp":"2022-12-25T12:44:48.289+00:00","status":500,"error":"Internal Server Error","path":"/posts/63a845a0a8b6dd70a1fa2462"}

4. Пост не отредактирован

** Окружение: Версия приложения: 1.2.0, Браузер: Google Chrome 108.0.5359.125 (64 бита), ОС: Windows 7 х64