== Отчет о проведении исследовательского тестирования от 18.12.2022
=== Краткое описание
За период с 16 по 18 декабря 2022 было проведено исследовательское тестирование приложения http://qa-games.ru/, согласно ранее разработанной стратегии (прилагаемый файл «Test_strategy.adoc»).

В процессе выполнения работы было изучено приложение, составлены и выполнены  тест-кейсы, а также зафиксированы ответы системы.

Результаты выполнения тест-кейсов  отображены в прилагаемом документе HW5_Report-table_1.adoc.

Тест-кейсы на проверку всех уровней системы отображены в прилагаемом файле Report-table_integration.adoc

Разработана визуализация части тест-кейсов компонентов GUI в виде графов причинно-следственных связей: https://disk.yandex.ru/i/TSxknM0utTAEQQ

Разработана визуализация части тест-кейсов проверяющих системную интеграцию в виде графов причинно-следственных связей:  https://disk.yandex.ru/i/v6DjA9QCvBpgyA

=== Потенциальные дефекты приложения
- Не удалось осуществить регистрацию нового пользователя, необходимо уточнить, работает ли возможность добавления нового пользователя и какие ограничения у полей  формы регистрации.

Потенциальный риск: Пользователи не смогут использовать приложение.

- Всплывающая ошибка при регистрации нового пользователя не дает информации, что именно сделано не так.

Потенциальный риск: Пользователь при регистрации получив несколько раз ошибку без пояснений и не поняв в чем причина отказа, вероятно, уйдет в другое приложение, где такой проблемы не возникает.

- Возможность редактировать и удалять посты других пользователей.
Необходимо уточнить, имеет ли пользователь user1@example.com
особые права (права на модерацию) или такими правами наделен любой пользователь.

Потенциальный риск: Пользователи рискуют потерять результат своей работы (посты) и выберут приложение, где их работу не сможет изменить или удалить кто угодно.

- Не удалось осуществить поиск по дате.

Потенциальный риск: Видимый элемент, который не выполняет своей потенциальной функции и при этом нарушает работу поиска негативно сказаться на репутации приложения и с большой вероятностью оттолкнет пользователей.

- Форма регистрации содержит текст "Зарегистрироваца", необходимо уточнить, является ли это опечаткой или сделано намеренно.

Потенциальный риск: Ошибка на главной странице может негативно сказаться на репутации приложения и оттолкнуть пользователей.

=== Выводы
* На текущий момент реализована только часть предполагаемого функционала:

- Создавать посты;
- Редактировать свои посты;
- Удалять свои посты;
- Просматривать добавленные другими пользователями посты;

* Функция осуществлять поиск по постам реализована не полностью.

Отсутствует возможность поиска по определенному периоду публикации, хотя графический интерфейс подразумевает такую возможность

* Функция регистрации нового пользователя не рабоатет.
